### ISSUE TITLE
[Question] Use alpine postgres image

### ISSUE THREAD

**Issue by lonix1** [taigaio/docker-taiga-5#7]
The sample `docker-compose` uses postgres.

Is it safe to use the alpine postgres image instead?

**Comment by lubo** [comment]
Hi. To my knowledge, the Alpine variant doesn't differ from the Debian variant in any way that's meaningful to the application, so I believe it's safe. I ran Debian variants in production, that's why the samples use them.

**Comment by lonix1** [comment]
Thanks for confirming.
